type Query {
		categories: [Category]
        meals: [Meal]
	}



type Category {
		id: ID!
		name: String
	}

input categoryInput{
      name: String
}

input updateCategoryInput{
    id: ID!
    name: String
}

input deleteCategoryInput{
    id: ID!
    name: String
}

type Mutation {
    createCategory(input: categoryInput): [Category]
    updateCategory(input: updateCategoryInput): [Category]
    deleteCategory(input: deleteCategoryInput): [Category]
}